version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - fborriello
  assignees:
  - fborriello
  labels:
  - configuration
  - update
  - dependencies
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
  target-branch: develop
  reviewers:
  - fborriello
  labels:
  - configuration
  - update
  - github-actions-lib