spring:
  output:
    ansi:
      enabled: ALWAYS
apiDoc:
  api:
    info:
      title: "BULL Tutorial"
      description: "Simple web application containing a service that uses BULL for the object transformation."
      version: "1.0"
      contact:
        name: "Fabio Borriello"
        email: "borriello.fabio@gmail.com"
springdoc:
  api-docs.path: "/api-docs"
  swagger-ui:
    enabled: true
    path: "/swagger-ui/"
---
movie:
  vat: 20
